[workspace]
members = [
    "rush",
    "rush-state",
    "rush-console",
    "rush-eval",
    "rush-exec",
]

[workspace.dependencies]
thiserror = "1.0.40"
anyhow = "1.0.70"
colored = "2.0.0"
crossterm = "0.26.1"
ratatui = "0.20.1"
fs-err = "2.9.0"
