[workspace]
members = ["rush", "rush-state", "rush-eval", "rush-exec", "rush-plugins"]

[workspace.dependencies]
thiserror = "1.0.40"
anyhow = "1.0.70"
crossterm = "0.26.1"
ratatui = "0.20.1"
ansi-to-tui = "3.0.0"
fs-err = "2.9.0"
bitflags = "2.1.0"
