name: deploy
on:
  push:
    branches-ignore:
      - main
jobs:
  test:
    name: Test and Compile shell
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - name: Build | Compile
        run: cargo check
      - name: Build | Test
        run: cargo test

